### ISSUE TITLE
Clarify what "ambassador" means

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/engineering-progression#193]
Further to #152 and #164, there is still disagreement around use of the term "ambassador". Rather than block merging the examples which help clarify the intention, this issue has been opened to capture, and eventually resolve, differences about the exact term used. Note that this is not in the beta milestone

**Comment by rowanmanning** [comment]
To help clarify, there is only one competency which contains the word "ambassador":

```yml
- id: 0777c050-8008-4e17-a437-f8de0be3bd55
  summary: Is an ambassador for their team across FT technology and colleagues in the rest of the business
  examples:
    - Positively represents their team in interactions with other people by seeking to understand their perspectives, values and needs
    - Consistently contributes to their team being positively perceived by stakeholders (or by other engineering teams to which they provide support)
  description: null
  level: mid-to-senior1
  area: leadership
  domain: null
```
