### ISSUE TITLE
Align wording of "production issue" competencies

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/engineering-progression#194]
We have two competencies that are now slightly misaligned:

```yaml
- id: 9b30c5f3-7925-4514-9f31-251b32daf1d3
  summary: Gets involved in fixing live incidents in production
  examples:
    - Notices that an AWS region is down so fails over to another region
    - Responds to alerts for services in production by investigating errors and beginning remedial action
    - Works as home teams' "ops cop", liaising with Operations and Reliability to restore a service
  description: null
  level: junior-to-mid
  area: technical
  domain: null
```

```yaml
- id: 07715459-0423-4507-bdf1-fc397507eec7
  summary: Leads on fixing production issues
  examples: []
  description: null
  level: mid-to-senior1
  area: technical
  domain: null
```

The second competency feels like it expands on the first, so the language should probably be consistent. The first competency was updated recently in #191, after a discussion in the working group meeting, I think we should just apply similar changes to the second.
