### ISSUE TITLE
S1 -> S2: feedback on Debugs and fixes complex bugs efficiently

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/engineering-progression#206]
From S1 workshop:

- Noted that the 'production incident' thread of competencies (present at lower levels) is not represented at S2
- The examples are arguably too heavy on cross-team working, showing initiative etc, which are perhaps not technical skills as such (more delivery, leadership or comms). Should the examples be more focused on the tech, with those other skills reflected elsewhere (there was other feedback that the comms & delivery sections of the competencies are very sparse)

**Comment by alicebartlett** [comment]
Let's take this one to our 3pm meeting

**Comment by rowanmanning** [comment]
Here are the competencies:

```
- id: 9b30c5f3-7925-4514-9f31-251b32daf1d3
  summary: Gets involved in fixing live incidents in production
  examples:
    - Notices that an AWS region is down so fails over to another region
    - Responds to alerts for services in production by investigating errors and beginning remedial action
    - Works as home teams' "ops cop", liaising with Operations and Reliability to restore a service
  description: null
  level: junior-to-mid
  area: technical
  domain: null

- id: 07715459-0423-4507-bdf1-fc397507eec7
  summary: Leads on fixing live incidents in production
  examples:
    - Takes proactive action when an incident is reported on a system they support and resolves it satisfactorily
    - "Responds to critical issues raised in #ft-tech-incidents taking the initiative to fix them and reports back"
  description: null
  level: mid-to-senior1
  area: technical
  domain: null
```
