### ISSUE TITLE
Feedback: S1 -> S2 Presents their team's work to others in the business

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/engineering-progression#213]
From S1 workshop:

- ~Why is this in leadership, not communications?~ RM: resolved in #243 
- Could do with an M->S1 equivalent e.g. with examples like 'presents to Group/Team meeting'

**Comment by alicebartlett** [comment]
There is a junior competency in Leadership too which is:

> Presents their own work clearly to a product owner or tech lead

So - I propose we:
- Add a M->S1 competency
- Move all three of these to communication

Any objections/concerns or shall I open a PR?

**Comment by alicebartlett** [comment]
https://github.com/Financial-Times/engineering-progression/pull/243

I drafted a competency for m->s1 but didn't commit it because im not sure it's actually any good. Here is is for discussion:

m->s1
```
  - id: 7cc876aa-fce5-414b-b0c0-b1b7602beea8
    summary: Presents their work to a group of other engineers
    examples:
      - Presents something they've done at a dev huddle
      - Presents something at a show-and-tell
    description: null
    level: junior-to-mid
    area: communication
    domain: null
```
I think the natural middle ground between "presents to tech lead" and "presents to business" is "presents to larger dev team" but is this really what we want? is it important enough for its own competency?
