### ISSUE TITLE
Taking stakeholder requirements competency is duplicated

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/engineering-progression#244]
Two very similar competencies in S1->S2: 

> Takes a stakeholder problem, investigates to understand it and proposes a solution

> Translates difficult business requirements into technical designs with stakeholders

Let's delete one of these

**Comment by rowanmanning** [comment]
Pasting in full competency details for context:

```yml
- id: 877d7313-d6de-44ae-80b4-5ed094ddf39a
  summary: Takes a stakeholder problem, investigates to understand it and proposes a solution
  examples: []
  description: null
  level: senior1-to-senior2
  area: delivery
  domain: null
```

```yml
- id: 7b2bacf1-ba46-464d-94e3-dc6f7c5edeb0
  summary: Translates difficult business requirements into technical designs with stakeholders
  examples: []
  description: null
  level: senior1-to-senior2
  area: technical
  domain: null
```
