### ISSUE TITLE
"Contributes to the personal development of more junior people" wording

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/engineering-progression#251]
The wording of the S1->S2 competency relating to this is more relaxed than M->S1 (contributes here, but responsibility at M->S1)

```yml
- id: 7e613602-fda1-43dc-94ca-83e17b24f42c
  summary: Contributes to the personal development of more junior people
  level: senior1-to-senior2
```

```yml
- id: 5e7b6a79-c553-4852-a5eb-97a6550f59da
  summary: Has responsibility for others’ professional development
  level: mid-to-senior1
```
