### ISSUE TITLE
Reconsider Competency "Threads"

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/engineering-progression#274]
In the [original proposal for the competency data structure](https://github.com/Financial-Times/engineering-progression/issues/1) (since updated - see the earliest edit of the issue description) we included an `expandsOn` property to help us explain how later competencies expand on earlier competencies. For example:

> Leads on fixing live incidents in production (Mid–Senior1)

expands on

> Gets involved in fixing live incidents in production (Junior–Mid)

This was removed due to the additional complexity it presented when we were initially writing up the competencies. I think there's a lot of value in keeping this relationship written down somewhere, now that we're past the alpha stage and approaching a stable product:
  - It would help us to keep an eye on the original intent of competencies – they were written to form threads through the levels but it's easy to accidentally break that with some rewording
  - All of the information on which competencies form threads are in the heads of the original Working Group. If there's a full rotation of people then this will be lost
  - Alice and I are currently working on competencies for web frontend and backend engineers, and once again we've naturally started working on competencies that expand on each other through the levels, it'd be nice not to lose this

## Proposal

@quarterto and I had a conversation about this and there are a couple of ways we could add the concept of threads into the competencies. We have come up with a few; we'd like feedback on these as well as suggestions for alternatives if you have one in mind.

### Proposal 1: `expandsOn`

The same as the original proposal, each competency can have an `expandsOn` property set to the ID of another competency. Example (with data structure simplified):

```yaml
- id: 9b30c5f3-7925-4514-9f31-251b32daf1d3
  summary: Gets involved in fixing live incidents in production
  expandsOn: null

- id: 07715459-0423-4507-bdf1-fc397507eec7
  summary: Leads on fixing live incidents in production
  expandsOn: 9b30c5f3-7925-4514-9f31-251b32daf1d3
```

#### Pros

  - Explicit and clear
  - Easy to validate that a competency with the given ID exists

#### Cons

  - Passing around UUIDs is a little painful
  - It's difficult to follow a thread when looking at the YAML file, it involves stepping through the whole thing
  - It's not immediately obvious that an earlier competency belongs to a thread
  - The threads can only be a tree expanding _outwards_ from an earlier competency – a later competency cannot expand on multiple earlier competencies

### Proposal 2: `thread` with user-friendly value

Each competency has an optional `thread` property, which is a human-readable string similar to the competency level, domain, or area. Competencies with the same `thread` value are linked together. Example (with data structure simplified):

```yaml
- id: 9b30c5f3-7925-4514-9f31-251b32daf1d3
  summary: Gets involved in fixing live incidents in production
  thread: live-production-incidents

- id: 07715459-0423-4507-bdf1-fc397507eec7
  summary: Leads on fixing live incidents in production
  thread: live-production-incidents
```

#### Pros

  - Human-readable
  - Searchable while working on the YAML file

#### Cons

  - It may be difficult to come up with a sensible name for some of the threads
  - It would be valid for threads to include multiple competencies from the same level and be less useful

### Proposal 3: `thread` with UUID

Each competency has an optional `thread` property, which is a UUID that does _not_ match a competency ID. Competencies with the same `thread` value are linked together. Example (with data structure simplified):

```yaml
- id: 9b30c5f3-7925-4514-9f31-251b32daf1d3
  summary: Gets involved in fixing live incidents in production
  thread: 8778b8e8-a26d-4d98-8e36-0346e11b0a5a

- id: 07715459-0423-4507-bdf1-fc397507eec7
  summary: Leads on fixing live incidents in production
  thread: 8778b8e8-a26d-4d98-8e36-0346e11b0a5a
```

#### Pros

  - Searchable while working on the YAML file
  - No need to think of human-readable names

#### Cons

  - Passing around UUIDs is a little painful
  - It may be difficult to come up with a sensible name for some of the threads
  - It would be valid for threads to include multiple competencies from the same level and be less useful
