### ISSUE TITLE
Competency change: merge debugging ones for m->s1

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/engineering-progression#48]
```yaml
  summary: Regularly and independently debugs and fixes bugs regardless of origin
  examples:
    - Picks up and debugs an urgent issue comes in to the team, despite having not 


  summary: Debugs and fixes complex issues
```

Proposal: 
Merge into a single `Regularly and independently debugs and fixes bugs regardless of origin and complexity`

Reasoning:
Not clear why they'd ever be separate (perhaps somebody can explain to me the thinking behind it)
Having a single one aids modelling the growth of the 'debugging' competency through the career stages
